jobs:
    include:
        - stage: test
          language: node_js
          node_js:
              - 11
              - 10
              - 8
              - 6
          before_install:
              - npm i -g codecov
          script:
              - npm run lint
              - npm run test:ci
          after_success:
              - codecov
          notifications:
              email:
                  on_success: never
                  on_failure: always
